version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  container-1:
    container_name: ${CONTAINER_1_NAME}
    image: 2048-game
    restart: unless-stopped
    ports:
      - "${CONTAINER_1_PORT}:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

  container-2:
    container_name: ${CONTAINER_2_NAME}
    image: 2048-game
    restart: unless-stopped
    ports:
      - "${CONTAINER_2_PORT}:8080"
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
